export const ADD_CONDUCTOR = 'ADD_CONDUCTOR';
export const DELETE_CONDUCTOR = 'DELETE_CONDUCTOR';
export const EDIT_CONDUCTOR = 'EDIT_CONDUCTOR';
export const LOGUEAR_CONDUCTOR = 'LOGUEAR_CONDUCTOR';
